# Generated by Django 6.1 on 2026-08-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_request', to='orders.order'),
        ),
    ]
