# Generated by Django 6.1 on 2026-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutrequest_status_alter_checkoutrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'FAILED')], default='processing', max_length=20),
        ),
    ]
